-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.equipos
(
    id_equipo serial NOT NULL,
    nombre_equipo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    entrenador_equipo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT equipos_pkey PRIMARY KEY (id_equipo)
);

CREATE TABLE IF NOT EXISTS public.equipos_grupos
(
    id_relacion serial NOT NULL,
    id_equipo integer,
    id_grupo integer,
    CONSTRAINT equipos_grupos_pkey PRIMARY KEY (id_relacion)
);

CREATE TABLE IF NOT EXISTS public.estadios
(
    id_estadio serial NOT NULL,
    nombre_estadio character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT estadios_pkey PRIMARY KEY (id_estadio)
);

CREATE TABLE IF NOT EXISTS public.fases
(
    id_fase serial NOT NULL,
    descripcion_fase character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT fases_pkey PRIMARY KEY (id_fase)
);

CREATE TABLE IF NOT EXISTS public.grupos
(
    id_grupo serial NOT NULL,
    descripcion_grupo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT grupos_pkey PRIMARY KEY (id_grupo)
);

CREATE TABLE IF NOT EXISTS public.partidos
(
    id_partido serial NOT NULL,
    id_eqlocal integer,
    id_eqvisitante integer,
    fecha_partido date,
    hora_partido time without time zone,
    id_estado integer,
    id_fase integer,
    CONSTRAINT partidos_pkey PRIMARY KEY (id_partido)
);

CREATE TABLE IF NOT EXISTS public.resultados_partidos
(
    id_resultado serial NOT NULL,
    id_partido integer,
    goles_eqlocal character varying(100) COLLATE pg_catalog."default" NOT NULL,
    goles_eqvisitante character varying(100) COLLATE pg_catalog."default" NOT NULL,
    resultadofinal character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT resultados_partidos_pkey PRIMARY KEY (id_resultado)
);

ALTER TABLE IF EXISTS public.equipos_grupos
    ADD CONSTRAINT id_equipo FOREIGN KEY (id_equipo)
    REFERENCES public.equipos (id_equipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.equipos_grupos
    ADD CONSTRAINT id_grupo FOREIGN KEY (id_grupo)
    REFERENCES public.grupos (id_grupo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.partidos
    ADD CONSTRAINT id_eqlocal FOREIGN KEY (id_eqlocal)
    REFERENCES public.equipos (id_equipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.partidos
    ADD CONSTRAINT id_eqvisitante FOREIGN KEY (id_eqvisitante)
    REFERENCES public.equipos (id_equipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.partidos
    ADD CONSTRAINT id_estadio FOREIGN KEY (id_estado)
    REFERENCES public.estadios (id_estadio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.partidos
    ADD CONSTRAINT id_fase FOREIGN KEY (id_fase)
    REFERENCES public.fases (id_fase) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.resultados_partidos
    ADD CONSTRAINT id_partido FOREIGN KEY (id_partido)
    REFERENCES public.partidos (id_partido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;